# Generated by Django 4.2.2 on 2023-06-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_register_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_user',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='register_user',
            name='phonenumber',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
