# Generated by Django 4.2.2 on 2023-06-23 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_order_product_sell_product_rent_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_login',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.register_user'),
        ),
    ]
