# Generated by Django 4.2.2 on 2023-06-23 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_order_user_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user_login',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.register_user'),
        ),
    ]
