# Generated by Django 4.2.2 on 2023-06-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_cart_user_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_club',
            name='images',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='register_user',
            name='images',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
