# Generated by Django 4.2.2 on 2023-06-24 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_events_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_user',
            name='address',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='Addmember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.register_club')),
                ('user_login', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.register_user')),
            ],
        ),
    ]
