# Generated by Django 4.2.2 on 2023-06-24 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_register_user_address_addmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='total_cart',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.cart'),
        ),
    ]
