# Generated by Django 4.2.2 on 2023-06-24 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_cart_total_payment_total_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='rentproduct_id',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.product_rent'),
        ),
    ]
