# Generated by Django 4.2.2 on 2023-06-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_cart_rentproduct_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.CharField(default='1', max_length=100, null=True),
        ),
    ]
