# Generated by Django 4.2.2 on 2023-06-26 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='club_login',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.register_club'),
        ),
    ]
