# Generated by Django 4.2.2 on 2023-06-26 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_posts_club_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='club_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.register_club'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='user_login',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.register_user'),
        ),
    ]
