# Generated by Django 4.2.2 on 2023-06-27 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_cart_price_cart_type_alter_requests_club_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default='1', max_length=100, null=True),
        ),
    ]
