# Generated by Django 4.2.2 on 2023-06-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_alter_cart_price_alter_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='images',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
