# Generated by Django 4.2.2 on 2023-08-07 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_alter_cart_price_alter_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='user_login',
        ),
        migrations.RemoveField(
            model_name='register_club',
            name='password',
        ),
        migrations.RemoveField(
            model_name='register_shop',
            name='password',
        ),
        migrations.RemoveField(
            model_name='register_user',
            name='password',
        ),
    ]
