# Generated by Django 4.2.2 on 2023-08-07 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_remove_posts_user_login_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rentcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('total', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rentorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default='1', null=True)),
                ('amount', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('rented_date', models.DateField(auto_now_add=True, null=True)),
                ('return_date', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(default='pending', max_length=100, null=True)),
                ('product_id', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.product_sell')),
                ('user_login', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.register_user')),
            ],
        ),
        migrations.CreateModel(
            name='Shopcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('total', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shoporder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default='1', null=True)),
                ('total', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('status', models.CharField(default='pending', max_length=100, null=True)),
                ('product_id', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.product_sell')),
                ('user_login', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.register_user')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rent_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_login',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='total_cart',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.AddField(
            model_name='shopcart',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.shoporder'),
        ),
        migrations.AddField(
            model_name='shopcart',
            name='product_id',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.product_sell'),
        ),
        migrations.AddField(
            model_name='shopcart',
            name='user_login',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.register_user'),
        ),
        migrations.AddField(
            model_name='rentcart',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.rentorder'),
        ),
        migrations.AddField(
            model_name='rentcart',
            name='product_id',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.product_sell'),
        ),
        migrations.AddField(
            model_name='rentcart',
            name='user_login',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.register_user'),
        ),
    ]
