# Generated by Django 4.2.2 on 2023-08-07 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_rentcart_rentorder_shopcart_shoporder_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentcart',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='rentorder',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='shopcart',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='shoporder',
            old_name='product_id',
            new_name='product',
        ),
    ]
