# Generated by Django 4.2.2 on 2023-08-08 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_rename_product_id_rentcart_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoporder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shoporder',
            name='quantity',
        ),
    ]
