# Generated by Django 4.2.2 on 2023-08-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_remove_shoporder_product_remove_shoporder_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_rent',
            name='rent',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product_sell',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
