# Generated by Django 4.2.2 on 2023-08-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_alter_product_rent_rent_alter_product_sell_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='total',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shoporder',
            name='total',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
