# Generated by Django 4.2.2 on 2023-08-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_alter_shopcart_total_alter_shoporder_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcart',
            name='user_login',
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='total',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shoporder',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
