# Generated by Django 4.2.2 on 2023-08-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_remove_shopcart_user_login_alter_shopcart_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_sell',
            name='stock',
            field=models.IntegerField(null=True),
        ),
    ]
