# Generated by Django 4.2.2 on 2023-08-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_product_sell_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='status',
            field=models.CharField(default='pending', max_length=100, null=True),
        ),
    ]
