# Generated by Django 4.2.2 on 2023-08-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_shopcart_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentorder',
            old_name='date',
            new_name='orderdate',
        ),
        migrations.RemoveField(
            model_name='rentcart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='rentorder',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='rentorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='rentorder',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='rentorder',
            name='rented_date',
        ),
        migrations.RemoveField(
            model_name='rentorder',
            name='return_date',
        ),
        migrations.AddField(
            model_name='rentcart',
            name='rented_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rentcart',
            name='return_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rentorder',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
