# Generated by Django 4.2.2 on 2023-08-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_rename_date_rentorder_orderdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentcart',
            name='user_login',
        ),
        migrations.AddField(
            model_name='rentcart',
            name='days',
            field=models.IntegerField(null=True),
        ),
    ]
