# Generated by Django 4.2.2 on 2023-08-09 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_remove_rentcart_user_login_rentcart_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentcart',
            name='product',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.product_rent'),
        ),
    ]
