# Generated by Django 4.2.2 on 2023-08-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_alter_rentcart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentcart',
            name='status',
            field=models.CharField(default='pending', max_length=100, null=True),
        ),
    ]
