# Generated by Django 4.2.2 on 2023-08-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_rentcart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentcart',
            name='rented_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='rentcart',
            name='return_date',
            field=models.DateField(null=True),
        ),
    ]
