# Generated by Django 4.2.2 on 2023-08-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_alter_rentcart_rented_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentcart',
            name='rented_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rentcart',
            name='return_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
