# Generated by Django 4.2.2 on 2023-08-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_alter_rentcart_rented_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentcart',
            name='days',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
