# Generated by Django 4.2.2 on 2023-08-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_alter_rentcart_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentcart',
            name='days',
            field=models.CharField(default=1, max_length=100, null=True),
        ),
    ]
