# Generated by Django 4.2.2 on 2023-08-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0037_alter_rentcart_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_club',
            name='about',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
