# Generated by Django 4.2.2 on 2023-08-09 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0038_register_club_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articlename', models.CharField(max_length=100, null=True)),
                ('article', models.CharField(max_length=100000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='articles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.article'),
        ),
    ]
