# Generated by Django 4.2.2 on 2023-08-09 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0039_article_posts_date_alter_posts_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='event',
        ),
    ]
