# Generated by Django 4.2.2 on 2023-08-09 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0040_remove_posts_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article',
            new_name='articles',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='articles',
        ),
        migrations.AddField(
            model_name='article',
            name='club_login',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.register_club'),
        ),
    ]
