# Generated by Django 4.2.2 on 2023-08-10 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0041_rename_article_article_articles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentorder',
            name='club_login',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.register_club'),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='club_login',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.register_club'),
        ),
    ]
