# Generated by Django 4.2.2 on 2023-08-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0042_rentorder_club_login_shoporder_club_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_user',
            name='bio',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
