# Generated by Django 4.2.2 on 2023-08-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0043_register_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='status',
            field=models.CharField(default='pending', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Addmember',
        ),
    ]
