# Generated by Django 4.2.2 on 2023-08-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0044_requests_status_delete_addmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='status',
            field=models.CharField(default='you have sent a join request', max_length=100, null=True),
        ),
    ]
