# Generated by Django 4.2.2 on 2023-08-11 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0046_alter_requests_status_participate'),
    ]

    operations = [
        migrations.AddField(
            model_name='participate',
            name='status',
            field=models.CharField(default='Nil', max_length=100, null=True),
        ),
    ]
