# Generated by Django 4.2.2 on 2023-08-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0048_alter_requests_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
