# Generated by Django 4.2.2 on 2023-08-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0049_alter_requests_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='route',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
