# Generated by Django 4.2.2 on 2023-08-13 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0050_events_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_rent',
            name='shop_name',
        ),
        migrations.AddField(
            model_name='product_rent',
            name='club_name',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.register_club'),
        ),
    ]
