# Generated by Django 4.2.2 on 2023-08-14 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0051_remove_product_rent_shop_name_product_rent_club_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participate',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeddback', models.CharField(max_length=10000, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.register_user')),
            ],
        ),
    ]
