# Generated by Django 4.2.2 on 2023-08-14 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0052_alter_participate_status_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feeddback',
            new_name='feedback',
        ),
    ]
