# Generated by Django 4.2.2 on 2023-09-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0053_rename_feeddback_feedback_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentcart',
            name='total',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
