# Generated by Django 4.2.11 on 2024-03-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0055_alter_rentcart_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentorder',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
