# Generated by Django 4.2.11 on 2024-04-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0056_rentorder_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_club',
            name='images',
        ),
        migrations.AddField(
            model_name='register_club',
            name='image',
            field=models.FileField(null=True, upload_to='file'),
        ),
        migrations.AddField(
            model_name='register_club',
            name='phonenumber',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
