# Generated by Django 5.2.9 on 2026-02-20 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0057_remove_register_club_images_register_club_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_club',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='register_club',
            name='image',
            field=models.FileField(null=True, upload_to='file/'),
        ),
    ]
