from django.contrib import admin
from django.urls import path
from app1 import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",views.index),
    path("login/",views.login),
    path("galleryuser/",views.galleryuser),
    path("register_user/",views.register_user),
    path("register_shop/",views.register_shop),
    path("register_club/",views.register_club),
    path("adminindex/",views.adminindex),
    path("shopindex/",views.shopindex),
    path("userindex/",views.userindex),
    path("clubindex/",views.clubindex),
    path("shopping/",views.shopping),
    path("rent/",views.rent),
    path("commonpage/",views.commonpage),
    path("add_pdt_sell/",views.add_pdt_sell),
    path("add_pdt_rent/",views.add_pdt_rent),
    path("shopcart/",views.shopcart),
    path("rentcart/",views.rentcart),
    path("shoppayment/",views.shoppayment),
    path("clubuser/",views.clubuser),
    path("userprofile/",views.userprofile),
    path("article/",views.article),
    path("joinrqst/",views.joinrqst),
    path("rejectrqst/",views.rejectrqst),
    path("acceptrqst/",views.acceptrqst),
    path("clubview/",views.clubview),
    path("viewrqst/",views.viewrqst),
    path("clubs/",views.clubs),
    path("addevent/",views.addevent),
    path("add_shopcart/",views.add_shopcart),
    path("add_rentcart/",views.add_rentcart),
    path("rentpayment/",views.rentpayment),
    path("editclub/",views.editclub),
    path("postarticle/",views.postarticle),
    path("postimage/",views.postimage),
    path("editprofile/",views.editprofile),
    path("clubsadmin/",views.clubsadmin),
    path("clubviewadmin/",views.clubviewadmin),
    path("removeclub/",views.removeclub),
    path("deleteshopcart/",views.deleteshopcart),
    path("deleterentcart/",views.deleterentcart),
    path("eventadmin/",views.eventadmin),
    path("eventuser/",views.eventuser),
    path("joinevent/",views.joinevent),
    path("shopapprove/",views.shopapprove),
    path("clubapprove/",views.clubapprove),
    path("acceptapproval/",views.acceptapproval),
    path("acceptapprovalshop/",views.acceptapprovalshop),
    path("clubclub/",views.clubclub),
    path("clubbu/",views.clubbu),
    path("editevents/",views.editevents),
    path("editevents2/",views.editevents2),
    path("deleteevents/",views.deleteevents),
    path("purchasehistory/",views.purchasehistory),
    path("purchasehistoryclub/",views.purchasehistoryclub),
    path("renthistory/",views.renthistory),
    path("renthistoryclub/",views.renthistoryclub),
    path("renttt/",views.renttt),
    path("viewrentpdt/",views.viewrentpdt),
    path("deleterent/",views.deleterent),
    path("deletesale/",views.deletesale),
    path("viewsalepdt/",views.viewsalepdt),
    path("articleuser/",views.articleuser),
    path("articleadmin/",views.articleadmin),
    path("ordershop/",views.ordershop),
    path("deliveryshop/",views.deliveryshop),
    path("ordershophistory/",views.ordershophistory),
    path("orderclub/",views.orderclub),
    path("deliveryclub/",views.deliveryclub),
    path("orderclubhistory/",views.orderclubhistory),
    path("viewparticipants/",views.viewparticipant),
    path("viewparticipants2/",views.viewparticipants2),
    path("addfeedback/",views.addfeedback),
    path("viewfeedback/",views.viewfeedback),
    path("memberships/",views.memberships),
    path("viewriders/",views.viewriders),
    path("shopprofile/",views.shopprofile),
    path("editshop/",views.editshop),
    path("accepteventparticipant/",views.accepteventparticipant),
    path("rejecteventparticipant/",views.rejecteventparticipant),
    path("approverent/",views.approverent),
    path("acceptrent/",views.acceptrent),
    path("rejectrent/",views.rejectrent),
    path("de/",views.de),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)